<a href="https://colab.research.google.com/github/Pradeepsuthar/GitsMLTrainig2020/blob/master/day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!cal # for calender

    January 2020      
Su Mo Tu We Th Fr Sa  
          1  2  3  4  
 5  6  7  8  9 10 11  
12 13 14 15 16 17 18  
19 20 21 22 23 24 25  
26 27 28 29 30 31     
                      


In [2]:
! cat /etc/issue # for checking os name

Ubuntu 18.04.3 LTS \n \l



In [3]:
!free -m # for checking ram in MB

              total        used        free      shared  buff/cache   available
Mem:          13022         522       10586           0        1913       12227
Swap:             0           0           0


In [4]:
!lscpu # for CPU check

Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  2
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               63
Model name:          Intel(R) Xeon(R) CPU @ 2.30GHz
Stepping:            0
CPU MHz:             2300.000
BogoMIPS:            4600.00
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            46080K
NUMA node0 CPU(s):   0,1
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single ssbd ibrs 

In [0]:
# Numpy 
# pip install numpy
import numpy as np

In [12]:
# len (dir(np))
# lets create 1D array
a1 = np.array([2,3,4,5])
a1

array([2, 3, 4, 5])

In [11]:
# lets create 2D array
a2 = np.array([[2,6,7],[3,5,9],[6,9,5],[3,11,2]])
a2

array([[ 2,  6,  7],
       [ 3,  5,  9],
       [ 6,  9,  5],
       [ 3, 11,  2]])

In [13]:
# to print 1st row
a2[0]

array([2, 6, 7])

In [15]:
# to print first element of 2D array
a2[0][0]

2

In [17]:
# 1st row
a2[0:2]

array([[2, 6, 7],
       [3, 5, 9]])

In [18]:
# 1st Column
a2[0:,0]

array([2, 3, 6, 3])

In [19]:
a2[0:,1]

array([ 6,  5,  9, 11])

In [21]:
a2[0:,0:2]

array([[ 2,  6],
       [ 3,  5],
       [ 6,  9],
       [ 3, 11]])

In [26]:
a2[1:3,1:]

array([[5, 9],
       [9, 5]])

In [30]:
a2[1:3,[0,2]]

array([[3, 9],
       [6, 5]])

In [43]:
a2[1::2,[0,2]]

array([[3, 9],
       [3, 2]])

In [44]:
# math operations
a2

array([[ 2,  6,  7],
       [ 3,  5,  9],
       [ 6,  9,  5],
       [ 3, 11,  2]])

In [47]:
x = a2+6
x

array([[ 8, 12, 13],
       [ 9, 11, 15],
       [12, 15, 11],
       [ 9, 17,  8]])

In [49]:
sum_of_2_arr = a2+x
sum_of_2_arr

array([[10, 18, 20],
       [12, 16, 24],
       [18, 24, 16],
       [12, 28, 10]])

In [50]:
sum_of_2_arr**3

array([[ 1000,  5832,  8000],
       [ 1728,  4096, 13824],
       [ 5832, 13824,  4096],
       [ 1728, 21952,  1000]])

In [51]:
sum_of_2_arr*3

array([[30, 54, 60],
       [36, 48, 72],
       [54, 72, 48],
       [36, 84, 30]])

In [52]:
sum_of_2_arr/2

array([[ 5.,  9., 10.],
       [ 6.,  8., 12.],
       [ 9., 12.,  8.],
       [ 6., 14.,  5.]])

In [53]:
sum_of_2_arr-2

array([[ 8, 16, 18],
       [10, 14, 22],
       [16, 22, 14],
       [10, 26,  8]])

In [54]:
# 10 rows and 7 columns with all zeros(0)
np.zeros((10,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [55]:
#ones
np.ones((10,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [56]:
# any number
np.full((10,7),7)

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])