<a href="https://colab.research.google.com/github/Pradeepsuthar/GitsMLTrainig2020/blob/master/machine_learning_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# !pip install scikit-learn

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9])
arr[2:6]

array([3, 4, 5, 6])

In [10]:
arr[0:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr[:5]

array([1, 2, 3, 4, 5])

In [12]:
a2 = np.array([[2,6,7],[3,5,9],[6,9,5],[3,11,2]])
a2

array([[ 2,  6,  7],
       [ 3,  5,  9],
       [ 6,  9,  5],
       [ 3, 11,  2]])

In [13]:
a2[0][0]

2

In [36]:
a2[0:,0:2]

array([[ 2,  6],
       [ 3,  5],
       [ 6,  9],
       [ 3, 11]])

In [40]:
a2[1:3,1:]

array([[5, 9],
       [9, 5]])

In [45]:
a2[0:,0::2]

array([[2, 7],
       [3, 9],
       [6, 5],
       [3, 2]])

In [46]:
a2[0::3,0:]

array([[ 2,  6,  7],
       [ 3, 11,  2]])

In [49]:
a2[1:3,0:2]

array([[3, 5],
       [6, 9]])